schema: ./src/graphql/schema.graphql
extensions:
  endpoints:
    Default GraphQL Endpoint:
      url: https://swapi-graphql.netlify.app/.netlify/functions/index
      #      url: http://localhost:4000/graphql
      headers:
        user-agent: JS GraphQL
        authorization: 1b93c259829f21790ad06655da7d90d8
      introspect: false


